services:
  - type: web
    name: algoarena-backend
    env: node
    region: oregon
    plan: free
    branch: Pasidu
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FIREBASE_PROJECT_ID
        value: algoarena-a3d46
      - key: FIREBASE_STORAGE_BUCKET
        value: algoarena-a3d46.appspot.com
      - key: FIREBASE_CLIENT_EMAIL
        value: firebase-adminsdk-fbsvc@algoarena-a3d46.iam.gserviceaccount.com
      - key: FIREBASE_PRIVATE_KEY
        sync: false
    healthCheckPath: /api/health
