{
  "name": "algoarena-backend",
  "env": "node",
  "buildCommand": "npm install",
  "startCommand": "npm start",
  "envVars": [
    {
      "key": "NODE_ENV",
      "value": "production"
    },
    {
      "key": "FIREBASE_PROJECT_ID",
      "value": "algoarena-a3d46"
    },
    {
      "key": "FIREBASE_STORAGE_BUCKET", 
      "value": "algoarena-a3d46.appspot.com"
    }
  ]
}
